AUTH_LOG = "/var/log/auth.log"
APACHE_LOG = "/var/log/apache2/access.log"

DATABASE_FILE = "mini_siem.db"

SSH_FAIL_THRESHOLD = 5
USERNAME_THRESHOLD = 3
WEB_404_THRESHOLD = 5

TIME_WINDOW_MINUTES = 10
AUTO_REFRESH_SECONDS = 5

ALERT_COOLDOWN_MINUTES = 5
